-- TABLE_CREATION_SCRIPTS.sql (copied to oracle-init/01_table_creation.sql)
-- Drops existing tables (if present) and creates the schema that matches the CSV headers.
-- This script is intentionally minimal and matches exactly the CSV-derived columns.

SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MONTHLY_STATS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TARIFFS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
/

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

CREATE TABLE TARIFFS (
  TARIFF_ID    NUMBER NOT NULL,
  NAME         VARCHAR2(200 CHAR) NOT NULL,
  MONTHLY_FEE  NUMBER(12,2) DEFAULT 0 NOT NULL,
  DATA_LIMIT   NUMBER(14,2) DEFAULT 0 NOT NULL,
  MINUTE_LIMIT NUMBER(10) DEFAULT 0 NOT NULL,
  SMS_LIMIT    NUMBER(10) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_TARIFFS PRIMARY KEY (TARIFF_ID)
);

CREATE TABLE CUSTOMERS (
  CUSTOMER_ID NUMBER NOT NULL,
  NAME        VARCHAR2(200 CHAR) NOT NULL,
  CITY        VARCHAR2(100 CHAR),
  SIGNUP_DATE DATE,
  TARIFF_ID   NUMBER,
  CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT FK_CUSTOMERS_TARIFF FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS (TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
  ID           NUMBER NOT NULL,
  CUSTOMER_ID  NUMBER,
  DATA_USAGE   NUMBER(14,2) DEFAULT 0,
  MINUTE_USAGE NUMBER(10) DEFAULT 0,
  SMS_USAGE    NUMBER(10) DEFAULT 0,
  PAYMENT_STATUS VARCHAR2(20),
  CONSTRAINT PK_MONTHLY_STATS PRIMARY KEY (ID),
  CONSTRAINT FK_MONTHLY_STATS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

COMMIT;
-- This file is mounted into the Oracle container and executed at startup to create schema and seed data.
-- It is intentionally identical to TABLE_CREATION_SCRIPTS.sql for automatic initialization.

@../TABLE_CREATION_SCRIPTS.sql
